// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwLDU32PWsMOgBMMs7D3p6S7UJbWj6V5g',
    appId: '1:64844799014:web:512590890fa1446d0a1ae7',
    messagingSenderId: '64844799014',
    projectId: 'chat-fd739',
    authDomain: 'chat-fd739.firebaseapp.com',
    storageBucket: 'chat-fd739.appspot.com',
    measurementId: 'G-9D4R8RTHLL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ57gDKUG05Q7guKGOR8fnnxmpI7aU2M0',
    appId: '1:64844799014:android:3460a3fc370fc8ca0a1ae7',
    messagingSenderId: '64844799014',
    projectId: 'chat-fd739',
    storageBucket: 'chat-fd739.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACPa59xPqb8KL2MYJXDN_GP0vM7JtCCc8',
    appId: '1:64844799014:ios:834e67296461f1a20a1ae7',
    messagingSenderId: '64844799014',
    projectId: 'chat-fd739',
    storageBucket: 'chat-fd739.appspot.com',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACPa59xPqb8KL2MYJXDN_GP0vM7JtCCc8',
    appId: '1:64844799014:ios:834e67296461f1a20a1ae7',
    messagingSenderId: '64844799014',
    projectId: 'chat-fd739',
    storageBucket: 'chat-fd739.appspot.com',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwLDU32PWsMOgBMMs7D3p6S7UJbWj6V5g',
    appId: '1:64844799014:web:d557fd8efbf9fda00a1ae7',
    messagingSenderId: '64844799014',
    projectId: 'chat-fd739',
    authDomain: 'chat-fd739.firebaseapp.com',
    storageBucket: 'chat-fd739.appspot.com',
    measurementId: 'G-DWWXTN62CB',
  );
}
